# Generated by Django 5.0.2 on 2024-02-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='descript',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
